### ISSUE TITLE
Working with the daemon

### ISSUE THREAD

**Issue by thecashewtrader** [tonyaldon/org-bars#7]
Great package!
I was wondering what kind of fix(es) would be required for it to work with the daemon.

**Comment by tonyaldon** [comment]
Thank you, I'm glad that you like `org-bars`.

I'm using org-bars with emacs daemon/client.

`org-bars` should work with emacs daemon/client.

Did you try it with emacs daemon/client?

If you tried it with emacs daemon/client and it did not work, can you be more specific on the problem you encountered? 

This way I could see what can I do.

Have a nice day.

**Comment by thecashewtrader** [comment]
Sorry for not being specific. On further research, it turns out that it's an issue with another package - `org-roam`, see https://www.reddit.com/r/OrgRoam/comments/qoohy7/how_to_prevent_or_mitigate_org_roam_opening_notes/ for more details. I will be closing the PR.

**Comment by tonyaldon** [comment]
No problem :)
